name: read4ever
description: "Turn scattered docs and guides into structured, trackable learning units."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # WebView
  flutter_inappwebview: ^6.1.5

  # Database
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.0

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.7

  # Data classes
  freezed_annotation: ^2.4.4

  # Fonts
  google_fonts: ^6.2.1

  # HTTP + XML
  http: ^1.2.2
  xml: ^6.5.0

  # Persistence
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  path: ^1.9.0

  # Share intent
  flutter_sharing_intent: ^2.0.0+5

  # External URL launching
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Codegen
  build_runner: ^2.4.12
  drift_dev: ^2.20.0
  flutter_launcher_icons: ^0.14.4
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: true
  ios: false
  windows:
    generate: false
    image_path: "assets/logo.png"
    icon_size: 48 # min: 48, max: 256, default: 48
  # adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21
  background_color_ios: "#FFFFFF"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/js/
